
log.info('postint loaded')
ore_dict.remove('gunpowder', item('mwc:sulfur_dust'))
ore_dict.remove('dustSulfur', item('mwc:sulfur_dust'))
ore_dict.remove('ingotCopper', item('mwc:copper_ingot'))
ore_dict.remove('ingotLead', item('mwc:lead_ingot'))
ore_dict.add('oreLimestone', item('chisel:limestone:*'))
ore_dict.add('oreLimestone', item('chisel:limestone1:*'))
ore_dict.add('oreLimestone', item('chisel:limestone2:*'))
crafting.removeByOutput(item('mwc:sulfur_dust'))
furnace.removeByInput(item('mwc:sulfur_dust:*'))
furnace.removeByInput(item('mwc:copper_ore:*'))
furnace.removeByInput(item('mwc:lead_ore:*'))
mods.jei.ingredient.hide(item('mwc:sulfur_dust'))
mods.jei.ingredient.hide(item('mwc:sulfur_ore'))
mods.jei.ingredient.hide(item('mwc:copper_ore'))
mods.jei.ingredient.hide(item('mwc:copper_ingot'))
mods.jei.ingredient.hide(item('mwc:lead_ore'))
mods.jei.ingredient.hide(item('mwc:lead_ingot'))